[solution]

energies_renouvelables_et_nucleaires = [
    "renouvelable",
    "solaire",
    "éolien",
    "biomasse",
    "géothermique",
    "hydraulique",
    "hydroélectrique",
    "photovoltaïque",
    "durabilité",
    "transition",
    "nucléaire",
    "propre",
    "thermique",
    "durable",
    "électricité",
    "électrique",
    "puissance",
    "stockage",
    "fission",
    "fusion",
]

transport_decarbone = [
    "véhicule",
    "électrique",
    "batterie",
    "commun",
    "transport",
    "hybride",
    "covoiturage",
    "vélo",
    "hydrogène",
    "aménagement",
    "mobilité",
    "routier",
    "ferroviaire",
    "électrification",
]

engagement_politique_et_entreprises = [
    "gouvernance",
    "législation",
    "accord",
    "engagement",
    "stratégie",
    "diplomatie",
    "acteurs",
    "lobbying",
    "participation",
    "responsabilité",
    "traités",
    "financement",
    "Paris",
    "régulation",
    "organisations",
    "politique",
    "économie",
    "projet",
    "loi",
    "certification",
    "investissement",
]

activisme_eco = [
    "militantisme",
    "mouvement",
    "écologie",
    "marches",
    "protestation",
    "défense",
    "environnement",
    "activisme",
    "engagement",
    "protection",
    "grève",
    "boycott",
    "mobilisation",
    "plaidoyer",
    "désobéissance",
    "civile",
    "dénonciation",
    "dénoncer",
    "action",
    "manifestation",
]

solution_innovante = [
    "technologie",
    "verte",
    "innovation",
    "développement",
    "produit",
    "nouvelle",
    "approche",
    "technologie",
    "propre",
    "recherche",
    "écoconception",
    "circulaire",
    "créativité",
    "créatif",
    "alternatif",
    "solution",
]

comportement_consommateur = [
    "consommateur",
    "consommation",
    "comportement",
    "style",
    "vie",
    "responsable",
    "durable",
    "minimalisme",
    "consciente",
    "équitable",
    "éthique",
    "locaux",
    "collaborative",
    "collectivité",
    "astuce",
]

reforestation = [
    "reboisement",
    "plantation",
    "replantation",
    "arbre",
    "reforestation",
    "carbone",
    "lutte",
    "régénération",
    "régénérer",
    "restauration",
    "forêt",
    "biodiversité",
    "reconstitution",
    "sylviculture",
    "boisement",
    "repeuplement",
    "repeupler",
]


[consequence]

catastrophes_naturelles = [
    "catastrophe",
    "naturelle",
    "inondation",
    "catastrophique",
    "phénomène",
    "cyclone",
    "séisme",
    "ouragan",
    "tempête",
    "dérégulation",
    "climatologie",
    "grêle",
    "vent",
    "typhon",
    "tornade",
    "tsunami",
]

rechauffement_climatique_canicule = [
    "réchauffement",
    "climatique",
    "chauffage",
    "température",
    "chaleur",
    "canicule",
    "chaud",
    "adaptation",
    "thermomètre",
    "extrême",
    "caniculaire",
]

secheresse = [
    "pénurie",
    "aridité",
    "déficit",
    "assèchement",
    "sols",
    "manque",
    "precipitations",
    "réserves",
    "désert",
    "sécheresse",
    "désertique",
    "déshydratation",
    "irrigation",
    "humidité",
]

couche_ozone = [
    "ozone",
    "appauvrissement",
    "trous",
    "chlorofluorocarbures",
    "Halons",
    "ultraviolet",
    "nocif",
    "rayonnement",
    "stratosphère",
]

feu_foret = [
    "incendies",
    "feu",
    "forêt",
    "pompier",
    "incontrôlé",
    "propagation",
    "fumée",
    "brulée",
    "étendue",
    "ardent",
    "incondescent",
    "pyromane",
]

tension_alim_famines = [
    "insécurité",
    "alimentaire",
    "famine",
    "malnutrition",
    "crise",
    "rareté",
    "besoins",
    "déficit",
    "sécurité",
    "affamé",
    "pénurie",
]

eau_potable = [
    "eau",
    "douce",
    "fraîche",
    "potable",
    "boire",
    "potable",
    "potabilité",
    "dégradation",
    "qualité",
    "crise",
    "raréfaction",
    "nappes",
    "phréatiques",
    "courante",
    "cristalline",
    "filtration",
    "purification",
    "assainissement",
]

hausse_niveau_mer_fonte_glace = [
    "hausse",
    "mer",
    "océan",
    "océanique",
    "niveau",
    "fonte",
    "montée",
    "élévation",
    "côte",
    "marée",
    "bloc",
    "glace",
    "iceberg",
    "glacier",
    "permafrost",
    "banquise",
    "dégel",
]

consequence_sociale = [
    "logement",
    "population",
    "déplacement",
    "conflit",
    "migration",
    "instabilité",
    "sociale",
    "mentale",
    "inégalité",
    "santé",
    "mode",
    "vie",
    "pauvreté",
    "communauté",
    "vulnérabilité",
    "précarité",
    "exclusion",
    "dépendance",
    "société",
    "humain",
]

acidification_ocean = [
    "acidification",
    "acidité",
    "pH",
    "carbonate",
    "calcium",
    "coraux",
    "marins",
    "mollusques",
    "coquilles",
    "plankton",
    "acidose",
    "océan",
]

perte_biodiversite = [
    "biodiversité",
    "espèces",
    "extinction",
    "disparition",
    "animaux",
    "plante",
    "végétation",
    "sauvage",
    "menacées",
    "menacé",
    "récolte",
    "cultures",
    "écologie",
    "marine",
    "terre",
    "réserve",
    "habitat",
    "corail",
    "écosystème",
    "conservation",
    "fragilité",
    "urgence",
]

pollution = [
    "air",
    "eau",
    "sol",
    "émissions",
    "gaz",
    "pollution",
    "polluant",
    "déchet",
    "toxique",
    "atmosphérique",
    "contamination",
    "industriel",
    "chimique",
    "résidus",
    "dégradation",
    "détritus",
]


[cause]

gaz_effet_de_serre = [
    "co2",
    "méthane",
    "protoxyde",
    "azote",
    "oxyde",
    "nitreux",
    "ozone",
    "chlorofluorocarbones",
    "hydrofluorocarbones",
    "perfluorocarbones",
    "soufre",
    "hexafluorure",
    "gaz",
    "émissions",
    "serre",
    "carbone",
    "dioxyde",
    "air",
    "fossile",
]

agriculture_et_utilisation_du_sol = [
    "agriculture",
    "sol",
    "changement",
    "érosion",
    "désertification",
    "dégradation",
    "aérosol",
    "pulvérisation",
    "bétail",
    "agricultures",
    "vache",
    "bovin",
    "culture",
    "rendement",
    "récolte",
    "engrais",
    "pesticide",
    "labour",
]

peche_et_chasse = [
    "poisson",
    "pêche",
    "chasse",
    "baleine",
    "disparition",
    "extinction",
    "espèces",
    "surpêche",
    "surchasse",
    "quota",
    "capture",
    "prédateur",
]

intrants_chimique_pollution_plastique = [
    "plastique",
    "pollution",
    "microplastique",
    "microplastiques",
    "plastiques",
    "déchets",
    "ordures",
    "détritus",
    "recyclage",
    "recycler",
    "chimique",
    "décharge",
    "industrielle",
    "contamination",
    "engrais",
]

surconsommation = [
    "surconsommation",
    "consommation",
    "comportement",
    "achat",
    "compulsif",
    "gaspillage",
    "excès",
    "superflu",
    "masse",
    "hyperconsommation",
    "style",
    "vie",
    "possession",
    "dépenser",
    "frénésie",
]

deforestation = [
    "déforestation",
    "forêt",
    "déboiser",
    "déforestier",
    "végétation",
    "arbre",
    "arbres",
    "végétal",
    "exploitation",
    "défrichement",
    "défricher",
    "abattage",
]
