data:
  root_dir: '/mounts/Datasets3/2024-2025-ChallengePlankton/train/'
  batch_size: 32
  num_workers: 8
  valid_ratio: 0.2
  sample_ratio: 1
  patch_size: 256
  stride: 128

# Default Loss : Focal Loss

optim:
  algo: Adam
  params:
    lr: 0.0002
  scheduler: True # Default Scheduler : CosineAnnealingLR

nepochs: 3

logging:
  wandb: 
    project: Kaggle
    entity: ratte-xavier-centralesupelec
  logdir: "/usr/users/sdim/sdim_34/panktonnet/logs/"  # Better to provide the fullpath, especially on the cluster

model:
  class: "Segformer"
  parameters:
    encoder_name: "resnet152"
    encoder_weights: "imagenet"